require_relative "./computer_move_spec"
require_relative "./opponents_spec"
require_relative "./winning_move_spec"
require_relative "./winner_spec"
require_relative "./difficulty_spec"
require_relative "./board_output_spec"
require_relative "./board_spec"
require_relative "./player_spec"